### PR TITLE
Make HTTP requests nice

### LINKED ISSUE #15: Make HTTP requests nice
- Don't aggressively retry failed HTTP requests to not cause traffic growth.
- Respect response headers, like `Retry-After`.
- Forbid redirects.

### PR DESCRIPTION
**Pull request by kalabukdima**
Closes #15

### CODE REVIEW

File: src/storage/downloader.rs [hunk 1]
```diff
@@ -88,6 +111,19 @@ impl ChunkDownloader {
...
                     self.cancel_tokens.remove(&chunk);
+                    match result {
+                        Ok(()) => {
+                            self.current_delay = Duration::from_secs(0);
+                        }
+                        Err(_) => {
+                            self.current_delay *= 2;
+                            let jitter = Duration::from_millis(rand::rng().random_range(50..150));
+                            self.current_delay = std::cmp::min(
+                                self.current_delay + jitter,
```
Comment (denisbsu) [inline src/storage/downloader.rs:122]: Not really a fan on jitter amplification (and jitter being base for delay progression), but at least it contained
